//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Tech Ninja Labs")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("2024")]
[assembly: System.Reflection.AssemblyDescriptionAttribute(".Net library to generate signed SAML 2.0 Response.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("3.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("3.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("Secure.SAML")]
[assembly: System.Reflection.AssemblyTitleAttribute("Secure.SAML")]
[assembly: System.Reflection.AssemblyVersionAttribute("3.0.0")]
[assembly: System.Reflection.AssemblyMetadataAttribute("RepositoryUrl", "https://github.com/TechNinjaLabs/Secure.SAML")]
// Generated by the MSBuild WriteCodeFragment class.

